package:
  name: ioos_qc
  version: "0.2.1"

source:
  path: ../

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - geojson
    - netCDF4
    - numba
    - numpy >=1.14
    - pygc
    - ruamel.yaml
    - shapely
    - simplejson
    - xarray

test:
  source_files:
    - ioos_qc
  imports:
    - ioos_qc

about:
  home: https://github.com/ioos/ioos_qc
  license: Apache 2.0
  license_file: LICENSE.txt
  summary: 'Collection of utilities, scripts and tests to assist in automated quality assurance.'
